### ISSUE TITLE
Adjustable vision distance for illumination conditions[FEATURE] 

### ISSUE THREAD

**Issue by sroakjp** [SalieriC/SWADE-Immersive-Macros#109]
**Is your feature request related to a problem? Please describe.**
Some settings impose a specific limitation on range of vision in low light conditions. For instance, in Pathfinder, in dim light vision is limited to 25"

**Describe the solution you'd like**
It would be nice if there was a setting to change the vision distance for different levels of illumination globally rather than individually by token.

**Comment by SalieriC** [comment]
Are you aware of any setting that uses different values? I'm thinking I could just change the low light range to 25" instead of introducing another setting. It sounds universal enough to me.

Regardless of setting or not, the question would be: What to do with Low Light Vision? It's not in SWPF so we have no clear indication about it.

**Comment by SalieriC** [comment]
Done, Release will be soon. I've settled on just using the SWPF ranges instead of making a setting for it. It was easier to implement and since SWPF is more clear on the matter it makes sense to do it like this. If I get complaints I'll reconsider adding a setting.
