### ISSUE TITLE
[BUG] Mighty Summoner ‘Dismiss’ dialog not working

### ISSUE THREAD

**Issue by Gallumph** [SalieriC/SWADE-Immersive-Macros#114]
I summon a creature, works like normal.  But then I select the creature and get the full "Summon New" dialog instead of the "Dismiss This Creature" Dialog.  Deleting the Active Effect manually dismisses the summon like normal.  Versions:  SWADE 2.2.2, SWIM 1.2.3

**To Reproduce**
1.  Select Summoner Token
2.  Use Mighty Summoner Macro
3.  Select any summon option, place Summon on the map (all working normally)
4.  Select the Summoned Token
5.  Use the Mighty Summoner Macro
6.  The full ‘Summon New’ dialog appears instead of the usual ‘Dismiss Thus Summons’ one.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: Chrome and Foundry
 - FVTT Version: 10.291
 - SWADE System Version: 2.2.2
 - SWIM Version:  1.2.3
 - Other Modules enabled?:  These are all my modules, however I did try it in a fresh world with only SWIM and it's dependencies installed, and could reproduce it.

![modules1](https://user-images.githubusercontent.com/124156680/216040782-e49b1379-8145-48b5-8ed7-6857333d9f2e.jpg)
![modules2](https://user-images.githubusercontent.com/124156680/216040791-c236869e-1007-46a3-b7af-68569c705686.jpg)

**Comment by SalieriC** [comment]
This is done now. Dismiss dialogue will be shown again and I moved over to using my own flags so this should be more resilient to changes in warpgate now. It won't work on already summoned tokens though, not sure how sensible it would be to create a migration for this. Probably would be a work of an hour or more and due to the short-lived nature of summoned creatures I think this isn't needed. Let me know if you think otherwise and I can create a macro for you that migrates already created tokens individually.
