### ISSUE TITLE
[BUG] Warnings

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#125]
![image](https://github.com/SalieriC/SWADE-Immersive-Macros/assets/4999783/d230f214-51c7-4fdb-b5c9-9bebae9dd721)

**Comment by SalieriC** [comment]
I would highly appreciate if you could use the template for issues instead of a screenshot and calling it a day. Thank you.
Anyway, this is a v11 error I suppose. I will look into it, thanks for reporting. More details would be highly appreciated though as they could help me fix that faster. Thank you for reporting though.

**Comment by Dac2564** [comment]
Bug warning if my IP address 192.168.01must be taking down. I will ony warn you once!!

**Comment by brunocalado** [comment]
The manifest is outdated. You just need to remove  "private": true, from it.

    {
      "label": "SWIM Roll Tables",
      "name": "swim-roll-tables",
      "path": "packs/swim-roll-tables.db",
      "system": "swade",
      "type": "RollTable",
      "private": true,
      "flags": {}
    }

**Comment by SalieriC** [comment]
Done, thank you for reporting.
