### ISSUE TITLE
[FEATURE] Add ability for Boost Trait to add other "non-skill" skills

### ISSUE THREAD

**Issue by steveculshaw** [SalieriC/SWADE-Immersive-Macros#128]
**Is your feature request related to a problem? Please describe.**
The existing selection of skills only has the current skills of the target, so there is no way to boost a skill that the character does not already have to a **d4**

(Checked [PEG](https://www.pegforum.com/forum/savage-worlds/official-answers-on-core-rules/45354-can-boost-trait-power-grant-a-skill-a-character-doesn-t-have) and it is valid to boost a non-existent skill.

**Describe the solution you'd like**
Add non-existent skills to selection list, although I can see this would make the list pretty long :-(

**Describe alternatives you've considered**
Add a second selection list with the full list of skills, and keep the "main" list for the character actual skill list

**Additional context**
N/A

**Comment by SalieriC** [comment]
SWADE currently does not allow this and doing this would require changes on SUCC that allow it. Due to the nature of the setting it would also likely require some form of manual input of the skills name as settings can add or remove the default skills. Not to mention spcialisations. This is a very complicated feature which I'd love to have but currently don't see a proper solution to unfortunately. I'm open to suggestions ofer on the [SUCC repo](https://github.com/SalieriC/SUCC/issues) though.
