### ISSUE TITLE
Unshake Macro does not work like rules as written

### ISSUE THREAD

**Issue by Razortide** [SalieriC/SWADE-Immersive-Macros#20]
Hey Salieri,

I am just playing around with the Unshake Macro (SWADE) and found it is not working like rules as written.

The rules state:
FAILURE: The character remains Shaken. She can only perform free actions.
SUCCESS: The character is no longer Shaken and may act normally.

Regarding Failure, the macro still removes Shaken, but it should leave it. Is this a House rule in effect?

**Comment by SalieriC** [comment]
Nope, that's a bug. Didn't realise that one because I dislike the new rules and never use them. I've pushed a quick hotfix, you can get the macro here until the next release: https://raw.githubusercontent.com/SalieriC/SWADE-Immersive-Macros/main/swim/macros/(Un-)Shake%20(SWADE).js
In the next release it will be included. Sorry for the inconvenience.
