### ISSUE TITLE
7.10 Broke Everything

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#23]
7.10 broke the macros...

![image](https://user-images.githubusercontent.com/4999783/119996712-63372700-bfa5-11eb-84c8-2467ea85cb8f.png)

**Comment by brunocalado** [comment]
The last line is doing this

![image](https://user-images.githubusercontent.com/4999783/120001132-d9d62380-bfa9-11eb-83f9-6cb86546b67a.png)

**Comment by SalieriC** [comment]
> 7.10 Broke Everything
It did indeed. :D
I'm almost done with the next full release so a hotfix will not happen but given the nature of the bug (thx for pointing it out btw) it is an easy fix. Also The Furnace users will not notice a damn thing.
I very much hope to get the next version wrapped up at the weekend but it kinda depends on https://github.com/javierriveracastro/betteroll-swade/issues/214 as it is the only thing holding me back atm.
Anyway, the macros are fixed in the dev version.
