### ISSUE TITLE
Using Ammo as Heat and single reloading

### ISSUE THREAD

**Issue by TheMOELANDER** [SalieriC/SWADE-Immersive-Macros#25]
Hi, I would need help in creating a solution for the following problems:

The Fanmade Savage Ghostbusters as well as some Mass Effect Conversions for SWADE use Heat Buildup instead of Ammunition. Every round the weapon is not used, it reduces one heat, basically autoreloading 1 Ammo when not in use. Is it possible to automate this?

Alternatively it would be good if there were a possibility to reload not the full amount of ammunition. Like in a Colt Single Action Army, where you have to reload every single bullet, would it be possible to reload fewer bullets than just the full amount? This would work well also in pirate scenarios, where "Revolvers" with more than 3 barrels have actually every single barrel loaded seperately.

**Comment by SalieriC** [comment]
> The Fanmade Savage Ghostbusters as well as some Mass Effect Conversions for SWADE use Heat Buildup instead of Ammunition. Every round the weapon is not used, it reduces one heat, basically autoreloading 1 Ammo when not in use. Is it possible to automate this?

So basically just counting shots up instead of down? That should be not a big deal but probably out of scope for this module. should be incredibly easy to do though. Just a few lines of code to edit in my ammo mgm macro.

> Alternatively it would be good if there were a possibility to reload not the full amount of ammunition. Like in a Colt Single Action Army, where you have to reload every single bullet, would it be possible to reload fewer bullets than just the full amount? This would work well also in pirate scenarios, where "Revolvers" with more than 3 barrels have actually every single barrel loaded seperately.

With you on that, this needs to be implemented soon. Will be after the next release though as I am only a few hours shy of releasing the next version. But it will be a focus to work on after that. Probably pretty easy to do as well.

Thanks for creating this ticket. =)

**Comment by TheMOELANDER** [comment]
It does not necessary need to count up for the Heat threshold. Ghostbusters uses it also the other way around: Slime blowers deplete the slime level, but since it's ectoplasmic culture it regenerates.
So basically it would be nice if "regenerating Ammo" could be a thing, where it only regenerates if it wasn't used in the same combat round.

**Comment by SalieriC** [comment]
That's unfortunately nothing I can reasonably do with macros, that'd need to be done in a module. That won't happen in SWIM, sorry. Anyway, everything I do will be separate for each individual weapon so having multiple weapons which function differently won't be an issue.

**Comment by TheMOELANDER** [comment]
That's great. As I said a single Shot reload or a 2 Shot reload would already be wonderful.

**Comment by SalieriC** [comment]
This is done in dev version now. To get it now (instead of waiting for the next update, you can copy it from here: https://raw.githubusercontent.com/SalieriC/SWADE-Immersive-Macros/main/swim/macros/Ammo%20Management%20(enhanced).js
Let me know if there are problems or if it doesn't suit your needs. In which case just reopen the issue. Let me know what you think. =)
Also don't miss out on the BR2 integration if you use BR2. It's quite nice.
**Keep in mind** that it is mandatory to read the documentation in order to use the macro: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/documentation/Ammo%20Management%20Setup.md
