### ISSUE TITLE
Spend Benny & Unshake (SWADE) macros will spend personal bennies for Extras

### ISSUE THREAD

**Issue by holgaph** [SalieriC/SWADE-Immersive-Macros#28]
I discovered that my "npc" actors start with 2 hidden bennies.  The "Spend Benny" and "Unshake (SWADE)" macros will inappropriately spend them.
Edit: same fix for "Unstun"
[macro-unstun.txt](https://github.com/SalieriC/SWADE-Immersive-Macros/files/6888203/macro-unstun.txt)

I've attached updated macros that fix this by testing for wildcards:
[macro-spend-benny.txt](https://github.com/SalieriC/SWADE-Immersive-Macros/files/6888162/macro-spend-benny.txt)
[macro-unshake-swade.txt](https://github.com/SalieriC/SWADE-Immersive-Macros/files/6888163/macro-unshake-swade.txt)

**Comment by SalieriC** [comment]
Yeah, this is actually a core problem related to this: https://gitlab.com/peginc/swade/-/issues/284
I am aware of this for a long time now. The reason why I did not do a check for Wild Card status is because Luck and Great Luck do not have Wild Card as a requirement, thus it is possible that non wild cards have their own bennies. So the macro should check for those present as well. Feel free to create a Merge Request in case you want to add this to the macros as well*. =)
Otherwise I'll get to that one macro at a time when I refactor all of them. This is however going to take a while as for now, I need to work on Spices & Flavours.

In the meantime here is a quick macro that patches all actors in a world: https://github.com/SalieriC/SWADE-Immersive-Macros/blob/main/swim/macros/benny_fixer.js
*This macros edge list might serve as a template for adding to the macros.

**Comment by holgaph** [comment]
Inserting the following after any instance of: "let bennies = token.actor.data.data.bennies.value;" should do the trick:


let actorLuck = token.actor.data.items.find(function (item) {return (item.name.toLowerCase() === "luck")});
let actorGreatLuck = token.actor.data.items.find(function (item) {return (item.name.toLowerCase() === "great luck")});

if ((!token.actor.data.data.wildcard) && (actorGreatLuck === undefined)) 
 {
 if ((!(actorLuck === undefined)) && (bennies > 1) && ((actorGreatLuck === undefined))) { bennies = 1; }
 else { bennies = 0; }
 }
// corrects for npc sheets "extras" defaulting to 2 bennies, accounting for Luck and Great Luck.

**Comment by SalieriC** [comment]
Done in Git now.
