### ISSUE TITLE
Chase macro doesnt load card images

### ISSUE THREAD

**Issue by QckSilverDragon** [SalieriC/SWADE-Immersive-Macros#29]
When using the Chase Setup macro, the cards it places down are white squares regardless of selected deck.

![image](https://user-images.githubusercontent.com/4044050/132972058-755288cd-7e06-47bc-9fc1-4c9481b0d056.png)

**Comment by SalieriC** [comment]
The issue is that it doesn't get the image. It currently uses `img: cardDraws[i].img,` as tile data but it should use `img: cardDraws[i].data.img,` for 0.8.9. That being said, there are numerous other issues that need to be resolved as well. The cards don't get deleted and the method for creating the tiles is soon to be deprecated. Those should all be fairly easy to fix. I'll get to it asap. Thanks for letting me know. =)

**Comment by SalieriC** [comment]
Done. The new macro will only work in 0.8.9 (or at least 0.8.x; I can't say for sure right now), I'll attack it here for everyone to grab until I push a new release. Do you have problems with any of the other macros @QckSilverDragon ?
[fvtt-Macro-chase-setup.zip](https://github.com/SalieriC/SWADE-Immersive-Macros/files/7149078/fvtt-Macro-chase-setup.zip)
