### ISSUE TITLE
Allow macros to work even if no bennies are left in case of common bond

### ISSUE THREAD

**Issue by SalieriC** [SalieriC/SWADE-Immersive-Macros#34]

**Comment by SalieriC** [comment]
I want to do this properly but I don't know what the best behaviour would be. I'd like to get some opinions from the community first. Here are the options I can think of (from easiest to most complicated to realise):

- Just allow a free reroll, assuming players will take care of spending the bennies on their own.
- Sending a request to the owner of a token/actor with Common Bond, initiating the roll on his end.
- Prompting the player with a dialogue to choose an actor/token with Common Bond and initiating the reroll, spending a Benny on behalf of the player who owns the actor/token with Common Bond.

**Comment by pmoore603** [comment]
In reading the rules, it doesn't state that it must be done for a specific roll (i.e. not necessarily in response to a roll, failed or otherwise).  It could be used for a soak, regaining power points, etc.  Theoretically, one could give away all their bennies at the start of a session, I guess.  If this is the case, the fourth option would be:

- Have a macro that confirms the player has Common Bond and bennies >0, and then opens a dialog that lets them choose an actor/token to give a benny to.  Then, the macro simply deducts and adds the benny to the other actor/token.  Then, that player uses whenever and however they see fit.

**Comment by SalieriC** [comment]
And that's exactly what I went for @pmoore603. Thanks for the suggestion. It's the easiest and most streamlined option. It could still interrupt the functions if a player gives away the Bennies too late but that's something I'll think about in a future release.
