### ISSUE TITLE
Fear Table resulting in a TypeError

### ISSUE THREAD

**Issue by pmoore603** [SalieriC/SWADE-Immersive-Macros#40]
Not sure if this is a bug or a problem in my environment, but I'm getting the following error when invoking the Fear Table script:

TypeError:  Cannot read properties of undefined (reading 'draw')

I think it is not finding the fear table, yet it is present under "SWADE Tables" from swade-core-rules.  In dev mode, game.tables only has one entry, which explains the error (it's not finding the table).

I changed a portion of code to be:

                    if (fearTableName) {
                        let fearTable = game.tables.getName(`${fearTableName}`)
                        if (fearTable) {
                            fearTable.draw({ roll });
                        } else {
                            ui.notifications.error("Unable to locate '" + fearTableName + "'.");
                            return;
                        }
                    }

And it is hitting the "Unable to locate..." error.

Seems like something is off in my world settings somehow.  Any ideas?

**Comment by SalieriC** [comment]
I'll investigate.

**Comment by SalieriC** [comment]
Okay so the problem here is that the table is in a compendium. The macro only gets tables inside the world. Searching tables in compendiums was suggested earlier in #15 but I didn't get to do this properly. I could do this in the light of #43 but I'm not sure what the best way to do it would be yet. I would need to do two selections, one for the compendium and one for the table. Having two options isn't supported by the native game settings though, so I would need to apply some HTML/HBS and possibly CSS as well. But I'd really, really like to avoid that. But I do see the value in it.

**Comment by SalieriC** [comment]
I've placed your warning on it (along with a plea to import the table into the world. For now this must suffice. Using tables from a compendium may come at a later date. In light of the most recent events at FVTT core development (preventing players to execute macros inside a compendium) however, I'm not so sure core even wants us to roll on tables in a compendium. This is less important here given that fear results are most likely rolled by the GM but it may be very relevant for stuff like Gritty Damage. I'll have to think about what the best practice would be here.
