### ISSUE TITLE
Shape-change creature controllable by other players

### ISSUE THREAD

**Issue by pmoore603** [SalieriC/SWADE-Immersive-Macros#57]
When one player shape changes, the focus for players (all, I assume) is changed to the newly shape-shifted token.  At this point, the other players are able to select and control the new token.

**Comment by SalieriC** [comment]
That sounds like a permission problem maybe resulting from multiple players having owner permission. I've added three lines to set owner permission for the newly created actor (it's in your repo already), could you check if it happens if players only have limited / observer permission for the preset?

**Comment by SalieriC** [comment]
With the improved permission management this should hopefully be fixed. It changes the permission of `scCopy` to the permissions of the original actor. Could you test please?
