### ISSUE TITLE
Jokers wild is broken for shape-shifted players

### ISSUE THREAD

**Issue by pmoore603** [SalieriC/SWADE-Immersive-Macros#59]
If a player is shape-shifted, jokers wild breaks:

- If the shifted player draws a joker, NOBODY gets any bennies.
- If a different player draws a joker, the shifted player does not get a benny (other players do).

**Comment by pmoore603** [comment]
Has to do with:  `token.data.disposition` and `actor.type`.

For players, `actor.type' needs to be "character", for players to get bennies.

Otherwise, for GM(s) to get bennies, `actor.type` needs to be "npc" and disposition needs to be hostile (CONST.TOKEN_DISPOSITIONS.HOSTILE = -1)

**Comment by SalieriC** [comment]
That sounds like a system problem then. Maybe they forgot about allied extras / assumed that allied extras would always share initiative with other players (which is a viable assumption ofc).
A way around this would be making `scCopy` type character on creation but I'm unsure if that could cause other issues. Maybe the best option would be to leave that to the GMs responsibility of setting up their presets as characters instead of NPCs.

**Comment by SalieriC** [comment]
I feel like I have opened pandora's box but I have added the `type` to the shape canger. Now NPCs will change into NPCs and PCs will change into PCs no matter what type the preset has. If that causes problems, please report asap.

**Comment by pmoore603** [comment]
Yes, definitely system behavior.  I'll give it a try.

**Comment by pmoore603** [comment]
Thinking further upon it, I think copying the type is the way to go as opposed to setting presets one way or the other.  Because this ability can be used by both PCs and NPCs.

Hopefully not a Pandora's box!  🤞
