### ISSUE TITLE
Macros are not working in other languages

### ISSUE THREAD

**Issue by Razortide** [SalieriC/SWADE-Immersive-Macros#64]
I found that macros are not working in other languages.

There are the minor issues that the macro is not translated (Fear Table, Unshake, Unstun, Soak Damage, Personal Health Centre) and major issues like Soak Damage, where the Injury Table will be used but the AE will come up empty (since no mapping exists)

If you give me a sample or an intro to move the hard coded english text to the en.json I will help tackle that.

**Comment by SalieriC** [comment]
I'm more interested in why the AEs aren't set up properly atm. I need more intel on that. How it works is: The function searches for matching keywords in the tables result text (like arm, guts, etc.) these should be localised and thus possible to find on tables in other languages. And then the AEs should be set up properly, provided the table and translation string keywords match.

The minor stuff is on the radar and will be done bit by bit as I said on discord. But I'm happy to give you a how to, doing so isn't difficult, just tedious. We'll talk on discord about it. =)

**Comment by Razortide** [comment]
So, I just checked again:
With English, it works fine, the wound will be applied as it should. In German it creates an injury called "undefined (permanent)" and no effects. I don't think it matters, but the rolled result was "Arm" which should be the same term then the English one :-)
There is no error message in the console.

**Comment by SalieriC** [comment]
I think it's a case issue. The way this works is: It takes the text of the result from the injury table. Then it makes the whole text lower case. And then it checks the text for the loca string content:
https://github.com/SalieriC/SWADE-Immersive-Macros/blob/50919839a341eaad47c614606ebb9b3bd8b1993d/swim/scripts/swim_modules/soak_damage.js#L347
In the en.json for this example it's `arm` in the german loca it's `Arm` meaning it won't match because of the capital `A`. The reason I'm doing it this way is because it seems to be rather common for some people to capitalise stuff in English even though it's not covered by the grammar. I could make the loca string lower case before comparing as well but at the time I created it that felt redundant.
So those are the possible solutions: Either change the entries in the loca or making it lower case in the code itself. I'm unsure what would be the best cause of action.

**Comment by Razortide** [comment]
If the localized files are not used anywhere else I would say I could redo them to lower case. On the other hand, if somebody else wants to localize SWIM to another language this might be a roadblock they probably will stumble upon. I guess, setting both values to lower case is the more efficient solution here.

**Comment by SalieriC** [comment]
You're probably right. I can't expect translators to check the complete code first to see how to set it up. I will change it.

**Comment by SalieriC** [comment]
Everything should be _functional_ in other languages now. A full translation is another issue.
