### ISSUE TITLE
[BUG] Remove Welcome Dialog

### ISSUE THREAD

**Issue by brunocalado** [SalieriC/SWADE-Immersive-Macros#87]
Hi.

Is it possible to turn off the welcome dialog by default? I know you can disable it with the check box. But, every new world or browser it show up again. Stream View + OBS don't save this, so every time I have to take care of it.

Tks

**Comment by SalieriC** [comment]
That's a core Foundry thing as Foundry stores that data in the browser rather than the server per user. I find that equally annoying but there is little I can do other than setting this dialogue to be world scoped.
Personally I think that user scoped settings should indeed be bound to that specific user and stored on the server rather than the users browser but there may be very good reasons not to do it like this. I'd suggest checking the Foundry GitHub about that and maybe creating an issue there: https://github.com/foundryvtt/foundryvtt

Until this changes I'm unfortunately very limited to what FVTT offers me in that regard and have to close this as won't fix. I'm terribly sorry about that.
